# Model arguments
model_name_or_path: /maas-vepfs/models/tulu-70b

# Data training arguments
dataset_mixer:
  # HuggingFaceH4/ultrafeedback_binarized: 1.0
  /maas-vepfs/outputs/tulu-70B/new_data/iter0: 1.0
  # maas-vepfs/outputs/tulu-70B/new_data/iter0: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# Trainer arguments
bf16: true
beta: 0.1
do_eval: false
evaluation_strategy: "no"
eval_steps: 100
gradient_accumulation_steps: 1
gradient_checkpointing: true
# hub_model_id: zephyr-7b-spin
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: linear
max_length: 1024
max_prompt_length: 512
num_train_epochs: 3
optim: rmsprop
output_dir: outputs
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
push_to_hub: false
save_strategy: "epoch"
save_total_limit: null
seed: 42
warmup_ratio: 0.1